name: weihua_flutter
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.13+14

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  sqflite: ^2.0.2+1
  provider: ^6.0.3
  get: ^4.6.5

  convert: ^3.0.2
  #  flutter_datetime_picker: ^1.5.1
  flutter_inapp_purchase: ^5.2.0
  platform: ^3.1.0
  launch_review: ^3.0.1

  #a~z 分组排序
  azlistview: ^2.0.0
  # 汉字转拼音
  lpinyin: ^2.0.3
  # 动态权限
  permission_handler: ^11.0.1
  event_bus: ^2.0.0
  # https://pub.dev/documentation/vibration/1.7.4-nullsafety.0/
  #  vibration: ^1.7.4-nullsafety.0
  audioplayers: ^5.2.1
  # Base Component
  # WebView iOS添加键值对 o.flutter.embedded_views_preview = YES
  #  https://pub.dev/packages/webview_flutter
  webview_flutter: ^3.0.4
  device_info_plus: ^9.1.0
  package_info_plus: ^5.0.1
  connectivity_plus: ^2.3.2
  gzx_dropdown_menu: ^3.1.0
  auto_size_text: ^3.0.0

  # Data
  #  json_annotation: ^2.4.0
  dio: ^4.0.5-beta1
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
  shared_preferences: ^2.0.15
  # 本地json对象存储
  localstorage: ^4.0.0+1

  # Html Encoder/Decoder
  html_unescape: ^2.0.0
  # 解析html标签
  #  flutter_html: ^1.0.2

  # 判断list是否相等
  collection: ^1.15.0
  #  crypto: ^2.0.6
  flutter_easyloading: ^3.0.5
  # UI
  oktoast: ^3.2.0
  pull_to_refresh: ^2.0.0
  #  flutter_swiper: ^1.1.6
  #  flutter_swiper_null_safety: ^1.0.2
  cached_network_image: ^3.2.1
  # 类iOS侧滑菜单
  flutter_slidable: ^1.3.0
  # 谁用谁闪亮
  shimmer: ^2.0.0
  # 识别图片的主要颜色
  #  palette_generator: ^0.2.0
  # 更新展示支持mark_down
  flutter_markdown: ^0.6.10+2
  flare_flutter: ^3.0.2


  # 复选框，选择器等部件 https://pub.dev/packages/smart_select
  #  smart_select: ^4.3.2

  # third_app
  # 启动第三方app
  url_launcher: ^6.1.2
  open_file: ^3.2.1

  # 日志打印  https://pub.dev/packages/logger
  logger: any

  # 屏幕适配
  flutter_screenutil: ^5.9.0
  crypto: ^3.0.2

  #bugly
  #  flutter_bugly: ^0.4.4
  fluwx: ^3.9.0+2
  #  flutter_sms: ^2.3.3
  image_picker: ^0.8.5+3
  extended_image: ^8.2.0
  flutter_svg: 1.1.0

#  flutter_contact: ^0.9.1+8
#  flutter_contact:
#    path: local_plugin_packages/flutter_contact

    #  https://flutter.cn/docs/development/packages-and-plugins/using-packages
  #  flutter_plugin_voip:
  #    git:
  #      url: http://shkjplus.cn:8010/flutter-group/flutter_plugin_voip.git
  #      ref: weihuaFlutterVoip
  #   ref: release/fluttervoip03

#  sqlite_viewer:
#    git:
#      url: https://hub.fastgit.org/hatemragab/flutter-sqlite-viewer.git

#dependency_overrides:
#  intl: ^0.17.0
dependency_overrides:
  intl: ^0.18.0
  pull_to_refresh:
    git:
      url: https://github.com/miquelbeltran/flutter_pulltorefresh
#  scrollable_positioned_list: ^0.3.2
  flutter_plugin_voip:
    git:
      url: http://shkjplus.cn:8010/flutter-group/flutter_plugin_voip.git
      ref: weihuaFlutterVoip


dev_dependencies:
  stack_trace: ^1.10.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

#  build_runner: ^1.6.2
#  json_serializable: ^3.1.0

flutter:

  uses-material-design: true

  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
    - family: kuaile # 站酷 快乐字体  https://fonts.google.com/?selection.family=Noto+Sans+SC&subset=chinese-simplified
      fonts:
        - asset: assets/fonts/ZCOOLKuaiLe-Regular.ttf
  assets:
    - assets/images/
    - assets/images/tab_letter_tip.png
    - assets/animations/
    - assets/regins.db
    - assets/call.mp3
    - assets/dtmf-0.aif
    - assets/dtmf-1.aif
    - assets/dtmf-2.aif
    - assets/dtmf-3.aif
    - assets/dtmf-4.aif
    - assets/dtmf-5.aif
    - assets/dtmf-6.aif
    - assets/dtmf-7.aif
    - assets/dtmf-8.aif
    - assets/dtmf-9.aif
    - assets/dtmf-s.aif
    - assets/dtmf-j.aif
#    - CHANGELOG.md

flutter_intl:
  enabled: true
